### ISSUE TITLE
[BUG] Can't use the wheel

### ISSUE THREAD

**Issue by DustyMonkey56** [iiDk-the-actual/FortniteEmoteWheel#13]
So basically the wheel doesn't open up when I hit B on my controllers and I don't really know why, I've tried to reinstall the mod but that doesn't seem to work

**Comment by brodyishim21** [comment]
same

**Comment by Persvicx** [comment]
you have to click RIGHT JOYSTICK DOWN.
B is for desktop.

**Comment by Kasspertheghost** [comment]
If your on a quest headset at all it just doesn't work. It sucks
