### ISSUE TITLE
[REQ] tutorial on how to add emotes to the asset bundle

### ISSUE THREAD

**Issue by MarshMellowGT** [iiDk-the-actual/FortniteEmoteWheel#14]
or just make the unity project of which u made the emotes on public

**Comment by MarshMellowGT** [comment]
ive literally been trying to make the asset bundle work with different emotes, but i could figure out a way

**Comment by Himothy318** [comment]
> or just make the unity project of which u made the emotes on public

How do you get the wheel I’m new just asking

**Comment by MarshMellowGT** [comment]
> > or just make the unity project of which u made the emotes on public
> 
> How do you get the wheel I’m new just asking

can u like ask somewhere else

**Comment by MarshMellowGT** [comment]
nvm i literally just figured it out, i have about every emote on the wheel now lmao

**Comment by coocboy420** [comment]
@MarshMellowGT how?

**Comment by Persvicx** [comment]
> nvm i literally just figured it out, i have about every emote on the wheel now lmao

can you please share how? ive been trying forever to get it to work for me

**Comment by MarshMellowGT** [comment]
> > nvm i literally just figured it out, i have about every emote on the wheel now lmao
> 
> can you please share how? ive been trying forever to get it to work for me

ur profile pic seems cool, so if we can dm eachother then ill show u

**Comment by MarshMellowGT** [comment]
@mellowfishy is my discord

**Comment by bfvrgames** [comment]
> @MellowFishy is my discord

Could you also tell me how please?
