### ISSUE TITLE
[BUG] Mod doesn't work at all

### ISSUE THREAD

**Issue by scoopermcpooper** [iiDk-the-actual/FortniteEmoteWheel#16]
The mod simply doesn't seem to work for me. I have the mod installed and placed in my BepInEx plugins folder, and I have also tried running the iiStupid installer from the discord. When I am in the game, and I click the joystick button or move it in any direction, the emote wheel doesn't pop up. I have tried every button on both controllers and nothing works. I have also tried pressing B on my keyboard but that doesn't work either.

**Comment by bfvrgames** [comment]
You have to have a working utilla for it to work.

**Comment by scoopermcpooper** [comment]
I have already got it to work because I found a video saying I need Utilla and TMPLoader, but do I only need Utilla or both these?
