### ISSUE TITLE
[REQ] Allow the making of custom emotes

### ISSUE THREAD

**Issue by Persvicx** [iiDk-the-actual/FortniteEmoteWheel#5]
We should be able to make custom emotes by porting them from fortnite or just anywhere and still being able to add sounds, icons and like a simple tutorial to make them.

They could be arranged in folders like (gamefiles)/FortniteEmotes/ and storing each one in a folder with its respective name, sound, icon, and animation.

I know some people wouldn't be smart enough to do it even with a tutorial but it would be nice for sharing emotes around to other people.

**Comment by iiDk-the-actual** [comment]
this is really hard for me to do with the way the code structure is sadly 💔
